# Pytorch Fundamental Exercise

## Imports

In [1]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

## Solutions

In [2]:
# Create a random tensor with shape (7, 7)
a = torch.rand(7,7)
a

tensor([[0.2086, 0.2155, 0.6144, 0.0527, 0.9477, 0.3342, 0.4487],
        [0.2757, 0.0282, 0.2739, 0.4364, 0.1169, 0.5301, 0.3917],
        [0.7408, 0.3088, 0.3885, 0.0302, 0.7255, 0.8859, 0.2133],
        [0.2679, 0.0616, 0.2226, 0.3446, 0.7226, 0.1533, 0.8805],
        [0.3313, 0.4255, 0.3186, 0.2200, 0.8062, 0.3884, 0.5282],
        [0.8136, 0.3844, 0.5476, 0.2281, 0.7203, 0.6674, 0.5916],
        [0.2470, 0.3196, 0.2422, 0.8739, 0.0924, 0.6990, 0.0207]])

In [3]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor)
b = torch.rand(1,7)
b

tensor([[0.0284, 0.5007, 0.4057, 0.2883, 0.7877, 0.3355, 0.6511]])

In [4]:
res1 = torch.matmul(a,b.T)
res2 = torch.matmul(b,a)
res1, res2

(tensor([[1.5290],
         [0.7838],
         [1.3495],
         [1.4219],
         [1.5243],
         [1.6799],
         [0.8381]]),
 tensor([[1.2165, 0.8355, 0.9687, 1.1504, 1.5249, 1.6635, 1.1772]]))

In [5]:
#Set the random seed to 0 and do exercises 2 & 3 over again
torch.manual_seed(0)
a = torch.rand(7,7)
torch.manual_seed(0)
b = torch.rand(1,7)
res1 = torch.matmul(a,b.T)
res2 = torch.matmul(b,a)
res1, res2

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752]]))

In [6]:
torch.cuda.manual_seed(1234)
a = torch.rand(2,3, device=device)
torch.cuda.manual_seed(1234)
b = torch.rand(2,3, device=device)
res1 = torch.matmul(a,b.T)
res1

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

In [7]:
res1.min(),res1.max(), res1.argmin(), res1.argmax()

(tensor(0.8358, device='cuda:0'),
 tensor(1.4578, device='cuda:0'),
 tensor(1, device='cuda:0'),
 tensor(3, device='cuda:0'))

In [8]:
torch.cuda.manual_seed(7)
a = torch.rand((1,1,1,10), device=device)
b = torch.squeeze(a)
a, a.shape, b, b.shape

(tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
            0.6333, 0.5733]]]], device='cuda:0'),
 torch.Size([1, 1, 1, 10]),
 tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
         0.5733], device='cuda:0'),
 torch.Size([10]))