# Pytorch Fundamental Exercise

## Imports

In [1]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

## Solutions

In [3]:
# Create a random tensor with shape (7, 7)
a = torch.rand(7,7)
a

tensor([[0.3181, 0.4843, 0.8746, 0.4638, 0.4209, 0.8313, 0.1065],
        [0.4475, 0.5417, 0.7295, 0.1663, 0.4885, 0.8831, 0.6722],
        [0.1504, 0.0807, 0.8404, 0.8825, 0.3805, 0.8893, 0.0186],
        [0.1768, 0.9199, 0.5550, 0.9529, 0.8266, 0.1321, 0.3548],
        [0.4901, 0.3511, 0.2107, 0.2153, 0.5547, 0.0352, 0.2321],
        [0.8007, 0.7544, 0.3950, 0.8015, 0.4258, 0.3024, 0.8069],
        [0.6086, 0.9990, 0.3818, 0.1849, 0.7068, 0.1792, 0.9427]])

In [4]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor)
b = torch.rand(1,7)
b

tensor([[0.0533, 0.4068, 0.8471, 0.8143, 0.4625, 0.9088, 0.4109]])

In [5]:
res1 = torch.matmul(a,b.T)
res2 = torch.matmul(b,a)
res1, res2

(tensor([[2.3264],
         [2.3023],
         [2.4631],
         [2.2779],
         [0.9066],
         [2.1402],
         [1.7898]]),
 tensor([[1.6748, 2.3221, 2.1205, 2.5199, 2.1506, 1.6291, 1.8118]]))

In [28]:
#Set the random seed to 0 and do exercises 2 & 3 over again
torch.manual_seed(0)
a = torch.rand(7,7)
torch.manual_seed(0)
b = torch.rand(1,7)
res1 = torch.matmul(a,b.T)
res2 = torch.matmul(b,a)
res1, res2

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752]]))

In [46]:
torch.cuda.manual_seed(1234)
a = torch.rand(2,3, device=device)
torch.cuda.manual_seed(1234)
b = torch.rand(2,3, device=device)
res1 = torch.matmul(a,b.T)
res1

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

In [47]:
res1.min(),res1.max(), res1.argmin(), res1.argmax()

(tensor(0.8358, device='cuda:0'),
 tensor(1.4578, device='cuda:0'),
 tensor(1, device='cuda:0'),
 tensor(3, device='cuda:0'))

In [51]:
torch.cuda.manual_seed(7)
a = torch.rand((1,1,1,10), device=device)
b = torch.squeeze(a)
a, a.shape, b, b.shape

(tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
            0.6333, 0.5733]]]], device='cuda:0'),
 torch.Size([1, 1, 1, 10]),
 tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
         0.5733], device='cuda:0'),
 torch.Size([10]))